name: Build and Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t node-hello-app .

    - name: Save Docker Image to Tarball
      run: docker save node-hello-app > node-hello-app.tar

    - name: Copy Docker Image to EC2
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "node-hello-app.tar"
        target: "~/"

    - name: SSH and Load Docker Image, Run Container
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo apt update -y
          sudo apt install curl -y
          sudo curl -SSL https://get.docker.com/ | sh
          sudo systemctl start docker
          sudo docker --version
          
          sudo docker load < node-hello-app.tar
          sudo docker rm -f node-hello-app || true
          sudo docker run -d --name node-hello-app -p 8080:8080 node-hello-app


